name: Create release
on:
  push:
    tags:
      - 'v*'
jobs:
  release:
    name: Tag
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up the required version of Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Import the GPG signing key
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo "$GPG_KEY" | base64 -d | gpg --batch --allow-secret-key-import --import
          gpg --keyid-format LONG --list-secret-keys
      -
        name: Create release
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ secrets.GPG_FINGERPRINT }}
