name: Test changes
on:
  pull_request:
    branches:
      - main
      - master
      - 'v*'
jobs:
  test:
    name: Pull Request
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout the repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up the required version of Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Import the GPG signing key
        id: import_gpg
        uses: danitso/ghaction-import-gpg@master
        with:
          gpg-private-key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      -
        name: Create release
        uses: danitso/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist --snapshot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
